name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git pkg-config libgtest-dev libgmock-dev
          # On some runners GTest isn't built -- build it
          cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib

      - name: Configure
        run: mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=$([[ "${{ matrix.compiler }}" == "clang" ]] && echo clang++ || echo g++) ..

      - name: Build
        run: cmake --build build -- -j

      - name: Run tests
        run: ctest --test-dir build --output-on-failure